# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Set up mega
      run: sudo apt install megatools
    - name: Sync sqlite
      run: mkdir data && cd data && megadl https://mega.nz/#!3NgEgYKC!A6FhXxa2yyyeJbOOg7CcWHZKDAlC1ULzAAAAAAAAAAA && ls
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run the app
      run: python3 grubby.py
    - name: Upload database
      uses: actions/upload-artifact@v2
      with:
        name: prices.sqlite3
        path: data/prices.sqlite3

  upload:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Set up mega
      run: sudo apt install megatools
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: prices.sqlite3
        path: /tmp
    - name: Debug
      run: ls /tmp
